### ISSUE TITLE
Implement ingestor `stat-changed` endpoint

### ISSUE THREAD

**Issue by jerome3o** [Runelite-Wrapped/runelite-wrapped#3]
This will require:
* Making a `StatChangedData` (or similar name) pydantic model
* Adding a POST endpoint to the ingestor service listening to `api/v1/event/stat-changed`
* That pushes the received data into the mongodb instance, into a "stat-changed" collection

You can use the `mock_client.py` script to test it

**Comment by jerome3o** [comment]
Example data found [here](https://github.com/jerome3o/runelite-wrapped/blob/7345baa7d08007c8e4a1e7ba1ab24f5deeec8889/src/ingestor/scripts/mock_client.py)

**Comment by Samueljbk** [comment]
Note for self: Run uvicorn on main and mock client script to test

**Comment by Samueljbk** [comment]
Done
