### ISSUE TITLE
Make a python function that calculates total ticks per player

### ISSUE THREAD

**Issue by jerome3o** [Runelite-Wrapped/runelite-wrapped#7]
in the `src/analytics/` directory make a `main.py` with a python function that:

* Take a username as an argument
* Pull all game tick data for that player
* Count the total number of game ticks
* Push that data to mongodb into a collection called `analytics.total_ticks` (or similar) with an object structure like:
```json
{
    "stat": "total_ticks",
    "timestamp": "{time stamp of calculation} i.e. use `import time; time.time()`",
    "value": 23423,
}
    
```

**Comment by Samueljbk** [comment]
Named collection "tick_count"

Removed stat from output and added username

Done
